sudo: required
language: generic 

services: 
   - docker 

before_install:
   - docker build -t kwilsonie/docker-react -f Dockerfile.dev . 

script:
   - docker run -e CI=true kwilsonie/docker-react npm run test 
   
