sudo: required
language: generic 

services: 
   - docker 

before_install:
   - docker build -t kwilsonie/docker-react -f Dockerfile.dev . 

script:
   - docker run -e CI=true kwilsonie/docker-react npm run test 

deploy:
   provider: elasticbeanstalk
   access_key_id: $AWS_ACCESS_KEY 
   secret_access_key:
       secure: "$AWS_SECRET_KEY"
   region: "eu-west-1"
   app: "docker-react"
   env: "DockerReact-env"
   bucket_name: "elasticbeanstalk-eu-west-1-071485204010"
   on:
      branch: master
